In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('C:/Users/Jcgoh/Desktop/school/1 Degree Sem 2/Machine learning/lab'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

C:/Users/Jcgoh/Desktop/school/1 Degree Sem 2/Machine learning/lab\Lab 1 - Introduction to Python I.pdf
C:/Users/Jcgoh/Desktop/school/1 Degree Sem 2/Machine learning/lab\Lab 2 - Introduction to Python II.pdf
C:/Users/Jcgoh/Desktop/school/1 Degree Sem 2/Machine learning/lab\Lab 3 - Introduction to Python III.pdf
C:/Users/Jcgoh/Desktop/school/1 Degree Sem 2/Machine learning/lab\dataset\1.docx
C:/Users/Jcgoh/Desktop/school/1 Degree Sem 2/Machine learning/lab\dataset\california.png
C:/Users/Jcgoh/Desktop/school/1 Degree Sem 2/Machine learning/lab\dataset\datasets.zip
C:/Users/Jcgoh/Desktop/school/1 Degree Sem 2/Machine learning/lab\dataset\housing.csv
C:/Users/Jcgoh/Desktop/school/1 Degree Sem 2/Machine learning/lab\dataset\iris.csv
C:/Users/Jcgoh/Desktop/school/1 Degree Sem 2/Machine learning/lab\dataset\titanic_train.csv
C:/Users/Jcgoh/Desktop/school/1 Degree Sem 2/Machine learning/lab\dataset\X_Y_Sinusoid_Data.csv
C:/Users/Jcgoh/Desktop/school/1 Degree Sem 2/Machine learning/lab\lab8\Ani

In [2]:
train_data=pd.read_csv('C:/Users/Jcgoh/Desktop/school/1 Degree Sem 2/Machine learning/lab/lab9/train.csv')
test_data=pd.read_csv('C:/Users/Jcgoh/Desktop/school/1 Degree Sem 2/Machine learning/lab/lab9/test.csv')

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from subprocess import check_output

In [4]:
train_data.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [5]:
x_train = train_data.drop(['label'], axis=1)
y_train = train_data['label']
x_test = test_data

In [6]:
x_train.shape, y_train.shape, x_test.shape

((60000, 784), (60000,), (10000, 784))

In [7]:
x_train = x_train.values.reshape(-1, 28, 28, 1)
x_train = x_train/255.0
x_test = x_test.values.reshape(-1, 28, 28, 1)
x_test = x_test/255.0
x_train.shape, x_test.shape

((60000, 28, 28, 1), (10000, 28, 28, 1))

In [8]:
y_train = tf.keras.utils.to_categorical(y_train,10)
y_train.shape

(60000, 10)

In [9]:
print(y_train[0:5,:])

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [10]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Conv2D(32,(3,3),activation = 'relu', input_shape=(28,28,1)),
  tf.keras.layers.Conv2D(32,(3,3),activation = 'relu'),
  tf.keras.layers.MaxPooling2D(2,2),
  tf.keras.layers.Conv2D(64,(3,3),activation = 'relu',padding = 'Same'),
  tf.keras.layers.Conv2D(64,(3,3),activation = 'relu',padding = 'Same'),
  tf.keras.layers.MaxPooling2D(pool_size = (2,2), strides = (2,2)),
  tf.keras.layers.Dropout(0.25),
  tf.keras.layers.Conv2D(64,(3,3),activation = 'relu',padding = 'Same'),
  tf.keras.layers.Conv2D(64,(3,3),activation = 'relu',padding = 'Same'),
  tf.keras.layers.MaxPooling2D(pool_size = (2,2), strides = (2,2)),
  tf.keras.layers.Dropout(0.25),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(256, activation='relu'),
  tf.keras.layers.Dense(256, activation='relu'),
  tf.keras.layers.Dropout(0.50),
  tf.keras.layers.Dense(10, activation='softmax')
])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 conv2d_1 (Conv2D)           (None, 24, 24, 32)        9248      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 12, 12, 32)       0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 12, 12, 64)        18496     
                                                                 
 conv2d_3 (Conv2D)           (None, 12, 12, 64)        36928     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 6, 6, 64)         0         
 2D)                                                    

In [11]:
class myCallback(tf.keras.callbacks.Callback):
        def on_epoch_end(self, epoch, logs={}):
            if(logs.get('accuracy') > 0.999):
                print("\nReached 99.9% accuracy so cancelling training!")
                self.model.stop_training = True
    
callbacks = myCallback()

In [ ]:
Optimizer = tf.keras.optimizers.Adam(
            learning_rate=0.0005, 
            beta_1=0.9, 
            beta_2=0.999, 
            epsilon=1e-07,
            name='Adam'
)
model.compile(optimizer=Optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, batch_size = 50, epochs = 20, callbacks=[callbacks])

Epoch 1/20
1200/1200 [==============================] - 74s 61ms/step - loss: 0.2661 - accuracy: 0.9137
Epoch 2/20
1200/1200 [==============================] - 75s 62ms/step - loss: 0.0693 - accuracy: 0.9791
Epoch 3/20
1200/1200 [==============================] - 75s 62ms/step - loss: 0.0517 - accuracy: 0.9852
Epoch 4/20
1200/1200 [==============================] - 75s 63ms/step - loss: 0.0404 - accuracy: 0.9884
Epoch 5/20
1200/1200 [==============================] - 74s 62ms/step - loss: 0.0357 - accuracy: 0.9899
Epoch 6/20
1200/1200 [==============================] - 74s 62ms/step - loss: 0.0302 - accuracy: 0.9911
Epoch 7/20
1200/1200 [==============================] - 78s 65ms/step - loss: 0.0265 - accuracy: 0.9926
Epoch 8/20
1200/1200 [==============================] - 90s 75ms/step - loss: 0.0243 - accuracy: 0.9928
Epoch 9/20
1200/1200 [==============================] - 89s 74ms/step - loss: 0.0214 - accuracy: 0.9940
Epoch 10/20
 744/1200 [=================>............] - ETA: 31

In [ ]:
results = model.predict(x_test)

results = np.argmax(results,axis = 1)

results = pd.Series(results,name="label")

In [ ]:
submission = pd.concat([pd.Series(range(1,28001),name = "ID"),results],axis = 1)

submission.to_csv("DNN 1201201564.csv",index=False)